'use strict';
const $=id=>document.getElementById(id);
const refs={game:{src:'art/game.jpg',label:'Existing wide candidate — composition/color reference, not cleared for scene action.'},detail:{src:'art/detail.jpg',label:'Existing macro candidate — rejected as a dominant story shot.'},raze:{src:'art/raze.png',label:'Existing Raze design — identity reference only.'}};
const gestures={'living-scene':'Establish the friends and their shared play space.','reaction-pair':'Shot → miss → friendly laughter.','shadow-reaction':'A cast shadow enters; both friends look toward its source.','frame-intrusion':'Raze crosses into the friends’ space. Vix blocks the exit.','action-triptych':'Net descends → friends visibly captured → group departs uphill.','eyeline-pair':'Abbie hears → sees her friends → decides to follow.','vertical-reveal':'Follow the same path up the mountain; settle at the starting point.','game-handoff':'Hold here for the player. One tap passes control to the host.'};
let data,index=0,elapsed=0,playing=false,last=0,handoffSent=false;
function list(id,values){$(id).replaceChildren(...values.map(value=>{const li=document.createElement('li');li.textContent=value;return li}))}
function render(){const s=data.scenes[index];$('count').textContent=`SCENE ${String(index+1).padStart(2,'0')} / 08`;$('duration').textContent=`${s.seconds}s · ${s.technique}`;$('scene-title').textContent=s.title;$('action').textContent=s.action;$('meaning').textContent=s.understand;$('emotion').textContent=s.emotion;for(const [id,key] of Object.entries({words:'text',sound:'sound',movement:'motion',transition:'transition',verdict:'verdict'}))$(id).textContent=s[key];list('visuals',s.visuals);list('needs',s.needs);$('actors').replaceChildren(...s.actors.map(name=>{const el=document.createElement('div');el.className='actor';el.textContent=name;return el}));$('gesture').textContent=gestures[s.technique];const ref=refs[s.reference];$('reference').hidden=!ref;if(ref){$('reference').src=ref.src;$('reference').alt=ref.label}else{$('reference').removeAttribute('src')}$('reference').style.display=ref?'block':'none';$('ref-label').textContent=ref?.label||'No compatible image selected. The diagram is blocking, not final art.';$('previous').disabled=index===0;$('next').textContent=index===data.scenes.length-1?'Preview handoff':'Next →';document.querySelectorAll('[data-scene]').forEach((b,i)=>b.setAttribute('aria-current',String(i===index)));tickUI();}
function tickUI(){$('clock').textContent=`${elapsed.toFixed(1)} / ${data.scenes[index].seconds}s`;$('play').textContent=playing?'Pause timing':'Play timing'}
function select(i){handoffSent=false;$('next').disabled=false;index=i;elapsed=0;playing=false;history.replaceState(null,'',`#${data.scenes[i].id}`);$('completion').textContent='';render()}
$('previous').onclick=()=>select(Math.max(0,index-1));$('next').onclick=()=>{if(index<data.scenes.length-1)select(index+1);else{if(handoffSent)return;handoffSent=true;$('next').disabled=true;playing=false;window.dispatchEvent(new CustomEvent('prologue:complete',{detail:{version:1,world:'marbleVoyage',preview:true}}));$('completion').textContent='Preview handoff emitted. This scaffold does not start the game.';tickUI()}};$('play').onclick=()=>{if(elapsed>=data.scenes[index].seconds)elapsed=0;playing=!playing;last=performance.now();tickUI()};
function frame(now){if(data&&playing&&!document.hidden){elapsed+=Math.min((now-last)/1000,.1);if(elapsed>=data.scenes[index].seconds){if(index<data.scenes.length-1){index++;elapsed=0;render()}else{elapsed=data.scenes[index].seconds;playing=false;}}tickUI()}last=now;requestAnimationFrame(frame)}
fetch('storyboard.json').then(r=>{if(!r.ok)throw Error('Story data unavailable');return r.json()}).then(value=>{data=value;$('scenes').replaceChildren(...data.scenes.map((s,i)=>{const b=document.createElement('button');b.dataset.scene=i;const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0');const title=document.createElement('b');title.textContent=s.title;b.append(n,title);b.onclick=()=>select(i);return b}));const requested=data.scenes.findIndex(s=>`#${s.id}`===location.hash);select(Math.max(0,requested));requestAnimationFrame(frame)}).catch(e=>{$('completion').textContent=e.message});
